required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
]

[[constraint]]
  name = "github.com/izumin5210/grapi"
  version = "v0.2.1"

[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  revision = "7951e5b80744558ae3363fd792806e1db15e91a4"
