// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package type_pb // import "github.com/izumin5210/grapi-playground/api/type_pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Book struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_f4c4fdbf4893690f, []int{0}
}
func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (dst *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(dst, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "izumin5210.sandbox.grapi_playground.type.Book")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_book_f4c4fdbf4893690f) }

var fileDescriptor_book_f4c4fdbf4893690f = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xcf, 0xcf,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xd2, 0xc8, 0xac, 0x2a, 0xcd, 0xcd, 0xcc, 0x33, 0x35,
	0x32, 0x34, 0xd0, 0x2b, 0x4e, 0xcc, 0x4b, 0x49, 0xca, 0xaf, 0xd0, 0x4b, 0x2f, 0x4a, 0x2c, 0xc8,
	0x8c, 0x2f, 0xc8, 0x49, 0xac, 0x4c, 0x2f, 0xca, 0x2f, 0xcd, 0x4b, 0xd1, 0x2b, 0xa9, 0x2c, 0x48,
	0x55, 0x32, 0xe5, 0x62, 0x71, 0xca, 0xcf, 0xcf, 0x16, 0x12, 0xe7, 0x62, 0x07, 0xe9, 0x8f, 0xcf,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0x44, 0xb8,
	0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x98, 0xc0, 0xc2, 0x10, 0x8e, 0x93, 0x49, 0x94, 0x51,
	0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0xc2, 0x36, 0x7d, 0xb0, 0x2d,
	0xba, 0x08, 0x5b, 0xf4, 0x13, 0x0b, 0x32, 0xf5, 0x41, 0x36, 0xc5, 0x17, 0x24, 0x25, 0xb1, 0x81,
	0x5d, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x33, 0x7d, 0x61, 0xb8, 0xab, 0x00, 0x00, 0x00,
}
