// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package internal_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _type "github.com/izumin5210-sandbox/grapi-playground/api/type"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListBooksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_27c6fc92b94f834a, []int{0}
}
func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (dst *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(dst, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

type ListBooksResponse struct {
	Books                []*_type.Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_27c6fc92b94f834a, []int{1}
}
func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (dst *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(dst, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*_type.Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type GetBookRequest struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_27c6fc92b94f834a, []int{2}
}
func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (dst *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(dst, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type CreateBookRequest struct {
	Book                 *_type.Book `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_27c6fc92b94f834a, []int{3}
}
func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (dst *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(dst, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetBook() *_type.Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateBookRequest struct {
	Book                 *_type.Book `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateBookRequest) Reset()         { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()    {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_27c6fc92b94f834a, []int{4}
}
func (m *UpdateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRequest.Unmarshal(m, b)
}
func (m *UpdateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRequest.Merge(dst, src)
}
func (m *UpdateBookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRequest.Size(m)
}
func (m *UpdateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRequest proto.InternalMessageInfo

func (m *UpdateBookRequest) GetBook() *_type.Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type DeleteBookRequest struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRequest) Reset()         { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()    {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_27c6fc92b94f834a, []int{5}
}
func (m *DeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRequest.Unmarshal(m, b)
}
func (m *DeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRequest.Merge(dst, src)
}
func (m *DeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRequest.Size(m)
}
func (m *DeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRequest proto.InternalMessageInfo

func (m *DeleteBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func init() {
	proto.RegisterType((*ListBooksRequest)(nil), "izumin5210.sandbox.grapi_playground.internal.ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "izumin5210.sandbox.grapi_playground.internal.ListBooksResponse")
	proto.RegisterType((*GetBookRequest)(nil), "izumin5210.sandbox.grapi_playground.internal.GetBookRequest")
	proto.RegisterType((*CreateBookRequest)(nil), "izumin5210.sandbox.grapi_playground.internal.CreateBookRequest")
	proto.RegisterType((*UpdateBookRequest)(nil), "izumin5210.sandbox.grapi_playground.internal.UpdateBookRequest")
	proto.RegisterType((*DeleteBookRequest)(nil), "izumin5210.sandbox.grapi_playground.internal.DeleteBookRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BookService service

type BookServiceClient interface {
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*_type.Book, error)
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*_type.Book, error)
	UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*_type.Book, error)
	DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := grpc.Invoke(ctx, "/izumin5210.sandbox.grapi_playground.internal.BookService/ListBooks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*_type.Book, error) {
	out := new(_type.Book)
	err := grpc.Invoke(ctx, "/izumin5210.sandbox.grapi_playground.internal.BookService/GetBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*_type.Book, error) {
	out := new(_type.Book)
	err := grpc.Invoke(ctx, "/izumin5210.sandbox.grapi_playground.internal.BookService/CreateBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*_type.Book, error) {
	out := new(_type.Book)
	err := grpc.Invoke(ctx, "/izumin5210.sandbox.grapi_playground.internal.BookService/UpdateBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/izumin5210.sandbox.grapi_playground.internal.BookService/DeleteBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookService service

type BookServiceServer interface {
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksResponse, error)
	GetBook(context.Context, *GetBookRequest) (*_type.Book, error)
	CreateBook(context.Context, *CreateBookRequest) (*_type.Book, error)
	UpdateBook(context.Context, *UpdateBookRequest) (*_type.Book, error)
	DeleteBook(context.Context, *DeleteBookRequest) (*empty.Empty, error)
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/izumin5210.sandbox.grapi_playground.internal.BookService/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/izumin5210.sandbox.grapi_playground.internal.BookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/izumin5210.sandbox.grapi_playground.internal.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/izumin5210.sandbox.grapi_playground.internal.BookService/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).UpdateBook(ctx, req.(*UpdateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/izumin5210.sandbox.grapi_playground.internal.BookService/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DeleteBook(ctx, req.(*DeleteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "izumin5210.sandbox.grapi_playground.internal.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBooks",
			Handler:    _BookService_ListBooks_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookService_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BookService_DeleteBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_book_27c6fc92b94f834a) }

var fileDescriptor_book_27c6fc92b94f834a = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0xca, 0xd3, 0x40,
	0x14, 0x25, 0xea, 0xd7, 0xda, 0x5b, 0xac, 0xed, 0xe0, 0x4f, 0x89, 0x0a, 0x25, 0x6e, 0xaa, 0x94,
	0x89, 0x46, 0xdc, 0x88, 0x28, 0xd4, 0x8a, 0x08, 0xae, 0x2a, 0x22, 0xba, 0x29, 0x13, 0x33, 0x86,
	0xa1, 0xe9, 0xcc, 0x98, 0x99, 0x88, 0x55, 0x44, 0xf0, 0x0d, 0xa4, 0x5b, 0x57, 0xbe, 0x92, 0xaf,
	0xe0, 0x63, 0xb8, 0x90, 0x99, 0x24, 0xa6, 0x35, 0x08, 0x8e, 0xf0, 0x2d, 0x93, 0x7b, 0xef, 0xb9,
	0x67, 0xce, 0x39, 0x5c, 0x80, 0x58, 0x88, 0x35, 0x96, 0xb9, 0xd0, 0x02, 0xcd, 0xd8, 0xfb, 0x62,
	0xc3, 0xf8, 0xed, 0xe8, 0xe6, 0x0d, 0xac, 0x08, 0x4f, 0x62, 0xf1, 0x0e, 0xa7, 0x39, 0x91, 0x6c,
	0x25, 0x33, 0xb2, 0x4d, 0x73, 0x51, 0xf0, 0x04, 0x33, 0xae, 0x69, 0xce, 0x49, 0xe6, 0x5f, 0x4e,
	0x85, 0x48, 0x33, 0x1a, 0x12, 0xc9, 0x42, 0xc2, 0xb9, 0xd0, 0x44, 0x33, 0xc1, 0x55, 0x89, 0xe5,
	0x5f, 0xaa, 0xaa, 0xf6, 0x2b, 0x2e, 0x5e, 0x87, 0x74, 0x23, 0xf5, 0xb6, 0x2a, 0x9e, 0xd5, 0x5b,
	0x49, 0xc3, 0x66, 0x73, 0x80, 0x60, 0xf8, 0x84, 0x29, 0x3d, 0x17, 0x62, 0xad, 0x96, 0xf4, 0x4d,
	0x41, 0x95, 0x0e, 0x5e, 0xc0, 0x68, 0xef, 0x9f, 0x92, 0x82, 0x2b, 0x8a, 0x16, 0x70, 0x64, 0xc6,
	0xd4, 0xd8, 0x9b, 0x9c, 0x9c, 0xf6, 0x23, 0x8c, 0xff, 0x85, 0xb2, 0xd9, 0x86, 0x0d, 0xce, 0xb2,
	0x1c, 0x0e, 0xae, 0xc1, 0xe0, 0x11, 0xb5, 0xc8, 0xd5, 0x32, 0x74, 0x11, 0xba, 0xa6, 0xb4, 0x62,
	0xc9, 0xd8, 0x9b, 0x78, 0xd3, 0xde, 0xb2, 0x63, 0x3e, 0x1f, 0x27, 0xc1, 0x73, 0x18, 0x3d, 0xc8,
	0x29, 0xd1, 0x74, 0xbf, 0x7b, 0x0e, 0xa7, 0x4c, 0xd9, 0xb6, 0xba, 0x93, 0xb0, 0xb3, 0x06, 0xf8,
	0x99, 0x4c, 0x8e, 0x01, 0x78, 0x06, 0xa3, 0x05, 0xcd, 0xe8, 0x21, 0xf0, 0xdf, 0xde, 0x17, 0xfd,
	0x3c, 0x82, 0xbe, 0x69, 0x7c, 0x4a, 0xf3, 0xb7, 0xec, 0x15, 0x45, 0x5f, 0x3d, 0xe8, 0xfd, 0x96,
	0x1d, 0xdd, 0xc3, 0x2e, 0x91, 0xc0, 0x7f, 0x7a, 0xe8, 0xdf, 0xff, 0xef, 0xf9, 0xd2, 0xef, 0x60,
	0xf0, 0xf9, 0xfb, 0x8f, 0xdd, 0x89, 0xd3, 0xa8, 0x63, 0xd3, 0xa2, 0xd0, 0x17, 0x0f, 0xba, 0x95,
	0x75, 0xe8, 0xae, 0x1b, 0xf8, 0xa1, 0xe3, 0xbe, 0xa3, 0xb8, 0xc1, 0xd8, 0x32, 0x41, 0x68, 0x58,
	0x32, 0x09, 0x3f, 0x54, 0x7a, 0x7e, 0x44, 0x3b, 0x0f, 0xa0, 0xc9, 0x08, 0x72, 0x7c, 0x73, 0x2b,
	0x5d, 0xce, 0xcc, 0xce, 0x59, 0x66, 0x83, 0xa0, 0xd2, 0xe8, 0x8e, 0x8d, 0x01, 0xfa, 0xe6, 0x01,
	0x34, 0x01, 0x73, 0x65, 0xd5, 0x8a, 0xa6, 0x33, 0xab, 0xab, 0x96, 0xd5, 0x95, 0xe8, 0xfc, 0xbe,
	0x5e, 0xb8, 0x16, 0xad, 0x22, 0xf9, 0x09, 0xa0, 0xc9, 0xaa, 0x2b, 0xc7, 0x56, 0xca, 0xfd, 0x0b,
	0xb8, 0xbc, 0x3a, 0xb8, 0xbe, 0x3a, 0xf8, 0xa1, 0xb9, 0x3a, 0xb5, 0x77, 0xd7, 0x5b, 0xde, 0xcd,
	0xcf, 0xbc, 0xec, 0xd7, 0x78, 0x2b, 0x19, 0xc7, 0x1d, 0x3b, 0x78, 0xeb, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1c, 0xa0, 0x0f, 0xee, 0x16, 0x05, 0x00, 0x00,
}
